// Banco de preguntas del Trivial del Mundial.
// Para AMPLIAR: añade más objetos al array. answer = índice (0-3) de la opción correcta.
// Mantén siempre 4 opciones y verifica que la respuesta sea correcta.

export type Question = { q: string; options: [string, string, string, string]; answer: 0 | 1 | 2 | 3 };

export const QUESTIONS: Question[] = [
  // ===== Preguntas base =====
  { q: "¿Qué selección ganó el Mundial de 2022 en Catar?", options: ["Francia", "Argentina", "Brasil", "Croacia"], answer: 1 },
  { q: "¿Quién ganó el Mundial de 2018 en Rusia?", options: ["Croacia", "Bélgica", "Francia", "Inglaterra"], answer: 2 },
  { q: "¿Qué país se proclamó campeón en Brasil 2014?", options: ["Alemania", "Argentina", "Brasil", "Países Bajos"], answer: 0 },
  { q: "¿Quién ganó el Mundial de Sudáfrica 2010?", options: ["Países Bajos", "España", "Alemania", "Uruguay"], answer: 1 },
  { q: "¿Qué selección levantó la Copa en Alemania 2006?", options: ["Francia", "Italia", "Alemania", "Portugal"], answer: 1 },
  { q: "¿Quién ganó el Mundial de Corea-Japón 2002?", options: ["Brasil", "Alemania", "Turquía", "Corea del Sur"], answer: 0 },
  { q: "¿Qué país ganó como anfitrión el Mundial de Francia 1998?", options: ["Brasil", "Croacia", "Francia", "Italia"], answer: 2 },
  { q: "¿Quién ganó el Mundial de Estados Unidos 1994?", options: ["Italia", "Brasil", "Suecia", "Bulgaria"], answer: 1 },
  { q: "¿Qué selección ganó Italia 1990?", options: ["Argentina", "Italia", "Alemania Occidental", "Inglaterra"], answer: 2 },
  { q: "¿Quién ganó el Mundial de México 1986?", options: ["Argentina", "Alemania Occidental", "Francia", "Brasil"], answer: 0 },
  { q: "¿Qué país ganó el primer Mundial de la historia, en 1930?", options: ["Argentina", "Brasil", "Uruguay", "Italia"], answer: 2 },
  { q: "¿Quién ganó el famoso Mundial de Inglaterra 1966?", options: ["Inglaterra", "Alemania Occidental", "Portugal", "Brasil"], answer: 0 },
  { q: "¿Dónde se celebró el Mundial de 2010?", options: ["Sudáfrica", "Brasil", "Alemania", "Catar"], answer: 0 },
  { q: "¿Qué dos países coorganizaron el Mundial de 2002?", options: ["China y Japón", "Corea del Sur y Japón", "Corea del Sur y China", "Japón y Tailandia"], answer: 1 },
  { q: "¿En qué país se jugó el Mundial de 1986?", options: ["Argentina", "España", "México", "Estados Unidos"], answer: 2 },
  { q: "¿Dónde se disputó el Mundial de 1982?", options: ["Italia", "España", "Argentina", "Francia"], answer: 1 },
  { q: "¿Qué país albergará junto a EE. UU. y México el Mundial de 2026?", options: ["Solo EE. UU.", "Canadá", "Costa Rica", "Cuba"], answer: 1 },
  { q: "¿Cuántas selecciones participan en el Mundial de 2026?", options: ["32", "40", "48", "64"], answer: 2 },
  { q: "¿Quién es el máximo goleador histórico de los Mundiales con 16 goles?", options: ["Ronaldo Nazário", "Miroslav Klose", "Gerd Müller", "Just Fontaine"], answer: 1 },
  { q: "¿Quién fue el máximo goleador del Mundial 2022?", options: ["Lionel Messi", "Kylian Mbappé", "Julián Álvarez", "Olivier Giroud"], answer: 1 },
  { q: "¿Qué jugador marcó un triplete en la final del Mundial 2022?", options: ["Lionel Messi", "Ángel Di María", "Kylian Mbappé", "Antoine Griezmann"], answer: 2 },
  { q: "¿Quién ganó la Bota de Oro del Mundial 2014 con 6 goles?", options: ["Thomas Müller", "Lionel Messi", "James Rodríguez", "Neymar"], answer: 2 },
  { q: "¿Qué país ha ganado más Mundiales (5)?", options: ["Alemania", "Italia", "Brasil", "Argentina"], answer: 2 },
  { q: "¿Cuántos Mundiales ganó Brasil?", options: ["3", "4", "5", "6"], answer: 2 },
  { q: "¿Qué jugador ha disputado más Mundiales como futbolista (5)?", options: ["Cristiano Ronaldo y Messi", "Lothar Matthäus y Rafa Márquez", "Buffon", "Maldini"], answer: 1 },
  { q: "¿A quién marcó Maradona el gol de la 'Mano de Dios' en 1986?", options: ["Brasil", "Inglaterra", "Alemania", "Bélgica"], answer: 1 },
  { q: "¿Qué hizo Zidane en la final de 2006 que acabó con su expulsión?", options: ["Un penalti fallado", "Un cabezazo a Materazzi", "Una mano", "Una falta al árbitro"], answer: 1 },
  { q: "¿Cómo se llamó el polémico 'Maracanazo' de 1950?", options: ["Brasil perdió la final en casa ante Uruguay", "Un gol fantasma", "Una final suspendida", "Un empate a cero"], answer: 0 },
  { q: "¿Quién falló el penalti decisivo de Italia en la final de 1994?", options: ["Franco Baresi", "Roberto Baggio", "Paolo Maldini", "Demetrio Albertini"], answer: 1 },
  { q: "¿Qué selección protagonizó el 'milagro' al ganar 1-0 a Alemania en la final de 1954?", options: ["Hungría", "Austria", "Alemania Occidental", "Uruguay"], answer: 2 },
  { q: "¿Con qué resultado ganó Alemania a Brasil en semifinales de 2014?", options: ["5-0", "7-1", "4-1", "6-1"], answer: 1 },
  { q: "¿Qué país eliminó a España en octavos del Mundial 2018 (por penaltis)?", options: ["Portugal", "Marruecos", "Rusia", "Croacia"], answer: 2 },
  { q: "¿Qué selección fue la gran sorpresa al llegar a semifinales en 2022?", options: ["Marruecos", "Senegal", "Japón", "Australia"], answer: 0 },
  { q: "¿Cómo se llama el trofeo que se entrega al campeón desde 1974?", options: ["Copa Jules Rimet", "Copa Mundial de la FIFA", "Copa de Oro", "Trofeo Pelé"], answer: 1 },
  { q: "¿Qué selección ganó tres veces y se quedó la antigua Copa Jules Rimet?", options: ["Italia", "Brasil", "Alemania", "Uruguay"], answer: 1 },
  { q: "¿Cada cuántos años se celebra la Copa del Mundo?", options: ["Cada 2 años", "Cada 3 años", "Cada 4 años", "Cada 5 años"], answer: 2 },
  { q: "¿Quién es el único portero que ha ganado el Balón de Oro de un Mundial?", options: ["Lev Yashin", "Oliver Kahn", "Iker Casillas", "Gianluigi Buffon"], answer: 1 },
  { q: "¿Qué jugador marcó 4 goles en una final de Mundial (1958, con 17 años destacó)?", options: ["Pelé", "Garrincha", "Vavá", "Didí"], answer: 0 },
  { q: "¿En qué Mundial debutó Pelé, ganándolo con solo 17 años?", options: ["1954", "1958", "1962", "1966"], answer: 1 },
  { q: "¿Qué país africano fue el primero en llegar a cuartos de final (1990)?", options: ["Nigeria", "Camerún", "Senegal", "Ghana"], answer: 1 },
  { q: "¿Qué selección perdió tres finales seguidas en los 70-80 antes de ganar?", options: ["Países Bajos", "Alemania Occidental", "Argentina", "Hungría"], answer: 1 },
  { q: "¿Quién marcó el gol más rápido en la historia de los Mundiales (11 segundos, 2002)?", options: ["Hakan Şükür", "Ronaldo", "Rivaldo", "Oliver Bierhoff"], answer: 0 },
  { q: "¿Qué país ganó su primer Mundial en 1998 siendo anfitrión?", options: ["Francia", "Italia", "España", "Inglaterra"], answer: 0 },
  { q: "¿Quién fue el capitán de Argentina campeona en 2022?", options: ["Ángel Di María", "Lionel Messi", "Nicolás Otamendi", "Rodrigo De Paul"], answer: 1 },
  { q: "¿Contra quién jugó Argentina la final de 2022?", options: ["Croacia", "Marruecos", "Francia", "Brasil"], answer: 2 },
  { q: "¿Cómo terminó el tiempo reglamentario + prórroga de la final de 2022?", options: ["2-2", "3-3", "1-1", "4-4"], answer: 1 },
  { q: "¿Qué país europeo ganó su primer Mundial en 2010?", options: ["Países Bajos", "España", "Portugal", "Bélgica"], answer: 1 },
  { q: "¿En qué Mundial se usó por primera vez el VAR?", options: ["2014", "2018", "2022", "2010"], answer: 1 },
  { q: "¿Qué jugador ganó el Balón de Oro al mejor jugador del Mundial 2022?", options: ["Kylian Mbappé", "Lionel Messi", "Luka Modrić", "Antoine Griezmann"], answer: 1 },
  { q: "¿Qué selección ganó el Mundial de 1978 como anfitriona?", options: ["Brasil", "Países Bajos", "Argentina", "Italia"], answer: 2 },
  { q: "¿Quién eliminó a Brasil en cuartos del Mundial 2006?", options: ["Francia", "Italia", "Alemania", "Portugal"], answer: 0 },

  // ===== TANDA NUEVA (+100) — respuestas repartidas por las 4 posiciones =====
  { q: "¿Qué selección perdió la final del Mundial 2014 ante Alemania?", options: ["Argentina", "Brasil", "Países Bajos", "Francia"], answer: 0 },
  { q: "¿Quién perdió la final de 2010 ante España?", options: ["Alemania", "Países Bajos", "Uruguay", "Portugal"], answer: 1 },
  { q: "¿Qué país perdió la final de 2006 ante Italia (en penaltis)?", options: ["Alemania", "Portugal", "Francia", "Brasil"], answer: 2 },
  { q: "¿Quién fue subcampeón en 2018, perdiendo ante Francia?", options: ["Bélgica", "Inglaterra", "Rusia", "Croacia"], answer: 3 },
  { q: "¿Qué selección perdió la final de 1998 ante Francia?", options: ["Brasil", "Italia", "Croacia", "Países Bajos"], answer: 0 },
  { q: "¿Cuántos Mundiales ha ganado Alemania (incluida Alemania Occidental)?", options: ["3", "4", "5", "2"], answer: 1 },
  { q: "¿Cuántos Mundiales ha ganado Italia?", options: ["2", "3", "4", "5"], answer: 2 },
  { q: "¿Cuántos Mundiales ha ganado Argentina?", options: ["2", "4", "1", "3"], answer: 3 },
  { q: "¿Cuántos Mundiales ha ganado Uruguay?", options: ["2", "1", "3", "4"], answer: 0 },
  { q: "¿Cuántos Mundiales ha ganado Francia?", options: ["1", "2", "3", "4"], answer: 1 },
  { q: "¿Cuántos Mundiales ha ganado España?", options: ["0", "2", "1", "3"], answer: 2 },
  { q: "¿Cuántos Mundiales ha ganado Inglaterra?", options: ["0", "2", "3", "1"], answer: 3 },
  { q: "¿Qué selección ganó el Mundial de 1970 en México?", options: ["Brasil", "Italia", "Uruguay", "Alemania Occidental"], answer: 0 },
  { q: "¿Quién ganó el Mundial de 1974?", options: ["Países Bajos", "Alemania Occidental", "Polonia", "Brasil"], answer: 1 },
  { q: "¿Qué país ganó el Mundial de 1982 en España?", options: ["Alemania Occidental", "Brasil", "Italia", "Polonia"], answer: 2 },
  { q: "¿Quién ganó el Mundial de 1962 en Chile?", options: ["Checoslovaquia", "Chile", "Yugoslavia", "Brasil"], answer: 3 },
  { q: "¿Qué selección ganó el Mundial de 1958 en Suecia?", options: ["Brasil", "Suecia", "Francia", "Alemania Occidental"], answer: 0 },
  { q: "¿Quién ganó el Mundial de 1954 en Suiza?", options: ["Hungría", "Alemania Occidental", "Austria", "Uruguay"], answer: 1 },
  { q: "¿Qué país ganó el Mundial de 1950?", options: ["Brasil", "Suecia", "Uruguay", "España"], answer: 2 },
  { q: "¿Quién ganó el Mundial de 1938?", options: ["Hungría", "Brasil", "Checoslovaquia", "Italia"], answer: 3 },
  { q: "¿Qué selección ganó el Mundial de 1934?", options: ["Italia", "Checoslovaquia", "Austria", "Hungría"], answer: 0 },
  { q: "¿Dónde se celebró el Mundial de 1970?", options: ["Brasil", "México", "Argentina", "España"], answer: 1 },
  { q: "¿En qué país se jugó el Mundial de 1974?", options: ["Países Bajos", "Suiza", "Alemania Occidental", "Italia"], answer: 2 },
  { q: "¿Dónde se disputó el Mundial de 1994?", options: ["México", "Canadá", "Brasil", "Estados Unidos"], answer: 3 },
  { q: "¿En qué país se celebró el Mundial de 2014?", options: ["Brasil", "Argentina", "Sudáfrica", "Uruguay"], answer: 0 },
  { q: "¿Dónde se jugó el Mundial de 1958?", options: ["Suiza", "Suecia", "Chile", "Inglaterra"], answer: 1 },
  { q: "¿En qué país fue el Mundial de 1962?", options: ["Argentina", "Brasil", "Chile", "Perú"], answer: 2 },
  { q: "¿Dónde se celebró el Mundial de 1954?", options: ["Suecia", "Italia", "Francia", "Suiza"], answer: 3 },
  { q: "¿En qué país se jugó el Mundial de 1934?", options: ["Italia", "Francia", "Uruguay", "España"], answer: 0 },
  { q: "¿Dónde se disputó el Mundial de 1938?", options: ["Italia", "Francia", "Alemania", "Suiza"], answer: 1 },
  { q: "¿En qué región del mundo se jugará el Mundial 2026?", options: ["Europa", "Sudamérica", "América del Norte", "Asia"], answer: 2 },
  { q: "¿Quién fue el máximo goleador del Mundial 2018 con 6 goles?", options: ["Cristiano Ronaldo", "Antoine Griezmann", "Romelu Lukaku", "Harry Kane"], answer: 3 },
  { q: "¿Quién ganó la Bota de Oro del Mundial 2010 con 5 goles?", options: ["Thomas Müller", "David Villa", "Wesley Sneijder", "Diego Forlán"], answer: 0 },
  { q: "¿Quién fue el máximo goleador del Mundial 2006?", options: ["Zinedine Zidane", "Miroslav Klose", "Hernán Crespo", "Lukas Podolski"], answer: 1 },
  { q: "¿Quién fue el Pichichi del Mundial 2002 con 8 goles?", options: ["Rivaldo", "Miroslav Klose", "Ronaldo", "Ronaldinho"], answer: 2 },
  { q: "¿Cuántos goles marcó Just Fontaine en el Mundial de 1958, récord en una sola edición?", options: ["9", "11", "15", "13"], answer: 3 },
  { q: "¿Quién marcó el gol que dio a España el Mundial 2010 en la prórroga?", options: ["Andrés Iniesta", "David Villa", "Xavi Hernández", "Fernando Torres"], answer: 0 },
  { q: "¿Quién marcó el gol de la victoria de Alemania en la final de 2014?", options: ["Thomas Müller", "Mario Götze", "André Schürrle", "Toni Kroos"], answer: 1 },
  { q: "¿Quién anotó dos goles de cabeza para Francia en la final de 1998?", options: ["Thierry Henry", "Emmanuel Petit", "Zinedine Zidane", "Youri Djorkaeff"], answer: 2 },
  { q: "¿Cuántos goles marcó Messi en el Mundial 2022?", options: ["5", "6", "8", "7"], answer: 3 },
  { q: "¿Cuántos goles marcó Mbappé en el Mundial 2022 (Bota de Oro)?", options: ["8", "6", "7", "9"], answer: 0 },
  { q: "¿Quién marcó el primer gol de la historia de los Mundiales (1930)?", options: ["Guillermo Stábile", "Lucien Laurent", "Héctor Castro", "Bert Patenaude"], answer: 1 },
  { q: "¿Quién ostentó el récord de goleador mundialista (15) antes de Klose?", options: ["Gerd Müller", "Pelé", "Ronaldo Nazário", "Just Fontaine"], answer: 2 },
  { q: "¿Quién anotó el llamado 'gol del siglo' ante Inglaterra en 1986?", options: ["Jorge Valdano", "Jorge Burruchaga", "Mario Kempes", "Diego Maradona"], answer: 3 },
  { q: "¿Qué portero soviético es apodado 'la Araña Negra'?", options: ["Lev Yashin", "Rinat Dasáyev", "Dino Zoff", "Gordon Banks"], answer: 0 },
  { q: "¿Qué jugador holandés popularizó el regate 'Cruyff turn' en 1974?", options: ["Johan Neeskens", "Johan Cruyff", "Ruud Krol", "Rob Rensenbrink"], answer: 1 },
  { q: "¿Qué selección impuso el 'fútbol total' en los Mundiales de los años 70?", options: ["Alemania Occidental", "Brasil", "Países Bajos", "Italia"], answer: 2 },
  { q: "¿Quién marcó el gol del triunfo de Alemania Occidental en la final de 1974?", options: ["Paul Breitner", "Franz Beckenbauer", "Uli Hoeneß", "Gerd Müller"], answer: 3 },
  { q: "¿Qué jugador inglés marcó un triplete en la final de 1966?", options: ["Geoff Hurst", "Bobby Charlton", "Martin Peters", "Roger Hunt"], answer: 0 },
  { q: "¿En qué Mundial se usaron por primera vez las tarjetas amarilla y roja?", options: ["1966", "1970", "1974", "1982"], answer: 1 },
  { q: "¿Qué selección africana alcanzó los cuartos de final en 2010?", options: ["Nigeria", "Costa de Marfil", "Ghana", "Argelia"], answer: 2 },
  { q: "¿Quién sacó un balón con la mano sobre la línea ante Ghana en 2010?", options: ["Diego Forlán", "Edinson Cavani", "Diego Lugano", "Luis Suárez"], answer: 3 },
  { q: "¿Quién marcó el penalti decisivo que dio el título a Argentina en 2022?", options: ["Gonzalo Montiel", "Lautaro Martínez", "Paulo Dybala", "Leandro Paredes"], answer: 0 },
  { q: "¿Qué portero argentino fue clave en la tanda de penaltis de la final 2022?", options: ["Franco Armani", "Emiliano Martínez", "Gerónimo Rulli", "Sergio Romero"], answer: 1 },
  { q: "¿Qué premio individual ganó el 'Dibu' Martínez en el Mundial 2022?", options: ["Balón de Oro", "Bota de Oro", "Guante de Oro", "Mejor joven"], answer: 2 },
  { q: "¿Quién tiene el récord de más partidos disputados en fases finales de Mundiales?", options: ["Lothar Matthäus", "Paolo Maldini", "Cristiano Ronaldo", "Lionel Messi"], answer: 3 },
  { q: "¿Quién ganó el Balón de Oro al mejor jugador del Mundial 2018?", options: ["Luka Modrić", "Kylian Mbappé", "Antoine Griezmann", "Eden Hazard"], answer: 0 },
  { q: "¿Qué jugador portugués disputó cinco Mundiales (2006-2022)?", options: ["Pepe", "Cristiano Ronaldo", "Nani", "Ricardo Quaresma"], answer: 1 },
  { q: "¿Cuántos Mundiales ganó Pelé en total?", options: ["1", "2", "3", "4"], answer: 2 },
  { q: "¿Qué jugador brasileño es apodado 'O Fenômeno'?", options: ["Ronaldinho", "Romário", "Rivaldo", "Ronaldo Nazário"], answer: 3 },
  { q: "¿Qué jugador marcó 5 goles en un solo partido del Mundial 1994?", options: ["Oleg Salenko", "Hristo Stoichkov", "Gabriel Batistuta", "Roberto Baggio"], answer: 0 },
  { q: "¿Qué veterano camerunés se hizo famoso por sus goles y bailes en los 90?", options: ["Samuel Eto'o", "Roger Milla", "Patrick Mboma", "Rigobert Song"], answer: 1 },
  { q: "¿Quién es considerado el goleador más joven en un Mundial?", options: ["Michael Owen", "Kylian Mbappé", "Pelé", "Lionel Messi"], answer: 2 },
  { q: "¿Qué seleccionador ganó el Mundial 2022 con Argentina?", options: ["Diego Simeone", "Mauricio Pochettino", "Jorge Sampaoli", "Lionel Scaloni"], answer: 3 },
  { q: "¿Qué seleccionador ganó el Mundial 2010 con España?", options: ["Vicente del Bosque", "Luis Aragonés", "Luis Enrique", "Julen Lopetegui"], answer: 0 },
  { q: "¿Qué entrenador ganó el Mundial 2014 con Alemania?", options: ["Jürgen Klinsmann", "Joachim Löw", "Hansi Flick", "Rudi Völler"], answer: 1 },
  { q: "¿Qué seleccionador llevó a Francia al título en 2018?", options: ["Laurent Blanc", "Raymond Domenech", "Didier Deschamps", "Aimé Jacquet"], answer: 2 },
  { q: "¿En qué año ganó Didier Deschamps el Mundial como jugador?", options: ["2000", "2006", "1994", "1998"], answer: 3 },
  { q: "¿Qué alemán ganó el Mundial como jugador (1974) y como entrenador (1990)?", options: ["Franz Beckenbauer", "Gerd Müller", "Lothar Matthäus", "Berti Vogts"], answer: 0 },
  { q: "¿Qué seleccionador italiano ganó el Mundial 2006?", options: ["Fabio Capello", "Marcello Lippi", "Cesare Prandelli", "Giovanni Trapattoni"], answer: 1 },
  { q: "¿Qué selección dio la sorpresa al ganar a Argentina en su debut en 2022?", options: ["México", "Polonia", "Arabia Saudí", "Australia"], answer: 2 },
  { q: "¿Qué selección asiática venció a Alemania y a España en la fase de grupos de 2022?", options: ["Corea del Sur", "Irán", "Catar", "Japón"], answer: 3 },
  { q: "¿Qué selección eliminó a Brasil en cuartos del Mundial 2022 (en penaltis)?", options: ["Croacia", "Argentina", "Países Bajos", "Marruecos"], answer: 0 },
  { q: "¿Contra quién jugó Marruecos las semifinales del Mundial 2022?", options: ["Argentina", "Francia", "Croacia", "Portugal"], answer: 1 },
  { q: "¿Qué puesto final logró Croacia en el Mundial 2022?", options: ["Subcampeón", "Cuarto puesto", "Tercer puesto", "Cuartos de final"], answer: 2 },
  { q: "¿En qué estadio se jugó la final del Mundial 2022?", options: ["Estadio 974", "Al Bayt", "Education City", "Estadio Lusail"], answer: 3 },
  { q: "¿Qué tuvo de histórico el Mundial de Catar 2022?", options: ["Primer Mundial en un país árabe", "Primer Mundial con 48 equipos", "Primer Mundial en África", "Primer Mundial sin prórrogas"], answer: 0 },
  { q: "¿En qué época del año (inusual) se disputó el Mundial 2022?", options: ["Junio-julio", "Noviembre-diciembre", "Enero-febrero", "Septiembre"], answer: 1 },
  { q: "¿Cuántos grupos habrá en la fase de grupos del Mundial 2026?", options: ["8", "10", "12", "16"], answer: 2 },
  { q: "¿Quiénes pasan seguro de cada grupo a la siguiente ronda en 2026?", options: ["Solo el primero", "Los tres primeros", "Todos", "Los dos primeros"], answer: 3 },
  { q: "¿Cuántos partidos en total tendrá el Mundial 2026?", options: ["104", "64", "80", "128"], answer: 0 },
  { q: "¿Qué tres países organizan el Mundial 2026?", options: ["EE. UU., México y Costa Rica", "EE. UU., Canadá y México", "Canadá, México y Cuba", "EE. UU., Canadá y Panamá"], answer: 1 },
  { q: "Respecto a los anfitriones, ¿qué tiene de novedoso el Mundial 2026?", options: ["Es el primero en América", "Es el primero en verano", "Es el primero con tres países anfitriones", "Es el primero con 32 equipos"], answer: 2 },
  { q: "¿Cómo se llama la primera ronda eliminatoria del Mundial 2026, con 32 equipos?", options: ["Octavos de final", "Cuartos de final", "Repesca", "Dieciseisavos de final"], answer: 3 },
  { q: "¿Cómo se llamaba el trofeo original del Mundial, entregado hasta 1970?", options: ["Copa Jules Rimet", "Copa FIFA", "Copa de Oro", "Copa Mundial"], answer: 0 },
  { q: "¿En honor a quién se nombró la primera copa del Mundial?", options: ["Un rey de Italia", "Un presidente de la FIFA", "Un futbolista uruguayo", "Un árbitro inglés"], answer: 1 },
  { q: "¿Qué selección ha participado en todos los Mundiales de la historia?", options: ["Alemania", "Italia", "Brasil", "Argentina"], answer: 2 },
  { q: "¿Cuál fue la mascota del Mundial de México 1986?", options: ["Juanito", "Naranjito", "Gauchito", "Pique"], answer: 3 },
  { q: "¿Cómo se llamó la mascota del Mundial de Inglaterra 1966, la primera de la historia?", options: ["Willie", "Tip y Tap", "Juanito", "Ciao"], answer: 0 },
  { q: "¿Cómo se llamó el icónico balón de Adidas del Mundial de 1970?", options: ["Tango", "Telstar", "Azteca", "Jabulani"], answer: 1 },
  { q: "¿De qué color es la tarjeta con la que un árbitro expulsa a un jugador?", options: ["Amarilla", "Verde", "Roja", "Azul"], answer: 2 },
  { q: "¿Cuántos jugadores tiene cada equipo en el campo?", options: ["10", "12", "9", "11"], answer: 3 },
  { q: "¿Qué selección fue la primera en ganar un Mundial fuera de su continente (1958)?", options: ["Brasil", "Uruguay", "Italia", "Argentina"], answer: 0 },
  { q: "¿Qué selección ha perdido tres finales de Mundial sin ganar ninguna?", options: ["Hungría", "Países Bajos", "Checoslovaquia", "México"], answer: 1 },
  { q: "¿Por qué no se celebraron Mundiales en 1942 y 1946?", options: ["Por una pandemia", "Por falta de dinero", "Por la Segunda Guerra Mundial", "Por boicot político"], answer: 2 },
  { q: "¿En qué década se celebró el primer Mundial?", options: ["Años 20", "Años 40", "Años 50", "Años 30"], answer: 3 },
  { q: "¿Qué selección ganó los Mundiales de 1934 y 1938 de forma consecutiva?", options: ["Italia", "Alemania", "Uruguay", "Brasil"], answer: 0 },
  { q: "¿Quién fue la primera selección en ganar dos Mundiales seguidos?", options: ["Brasil", "Italia", "Uruguay", "Alemania"], answer: 1 },
  { q: "¿Qué selección ganó dos Mundiales consecutivos en 1958 y 1962?", options: ["Italia", "Alemania Occidental", "Brasil", "Argentina"], answer: 2 },
  { q: "¿Qué selección ha disputado más finales de Mundial (8)?", options: ["Brasil", "Italia", "Argentina", "Alemania"], answer: 3 },
];
